project 'RecipleaseV1.xcodeproj'

# Uncomment the next line to define a global platform for your project
 platform :ios, '12.1'

target 'RecipleaseV1' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire'
  # Pods for RecipleaseV1

end
